const PDFDocument = require('pdfkit');

const fmtRM = (v) => `RM ${Number(v || 0).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

// Pipe a claim PDF into res (Express response).
function buildClaimPdf(res, { claim, items, tenant }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${claim.claim_number}.pdf"`);
  doc.pipe(res);

  const W = doc.page.width - 100; // usable width

  // ── Header ──────────────────────────────────────────────────
  doc.fontSize(18).font('Helvetica-Bold').text(tenant.company_name || 'ContractOS', 50, 50);
  if (tenant.address) doc.fontSize(9).font('Helvetica').text(tenant.address, 50, 72);
  if (tenant.phone) doc.fontSize(9).text(`Tel: ${tenant.phone}`);
  if (tenant.ssm_number) doc.fontSize(9).text(`SSM: ${tenant.ssm_number}`);

  doc.fontSize(20).font('Helvetica-Bold')
     .text('PROGRESS CLAIM'.replace('PROGRESS', claim.claim_type.toUpperCase()), 400, 50, { align: 'right' });

  doc.moveTo(50, 120).lineTo(545, 120).lineWidth(2).stroke('#1F3864');

  // ── Claim meta ──────────────────────────────────────────────
  doc.y = 132;
  const leftCol = 50, rightCol = 300;
  const row = (label, val, x = leftCol) => {
    doc.fontSize(9).font('Helvetica-Bold').text(label, x, doc.y, { continued: true })
       .font('Helvetica').text(`  ${val}`);
  };
  row('Claim No:', claim.claim_number);
  row('Project:', claim.project_name || '—');
  row('Claim Type:', claim.claim_type.charAt(0).toUpperCase() + claim.claim_type.slice(1));
  row('Claim Date:', fmtDate(claim.claim_date));
  row('Submitted By:', claim.submitted_by_name || '—');
  row('Status:', claim.status.toUpperCase());
  if (claim.notes) {
    doc.moveDown(0.3);
    row('Notes:', claim.notes);
  }

  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(0.5).stroke('#AAAAAA');
  doc.moveDown(0.5);

  // ── Line items table ─────────────────────────────────────────
  if (items && items.length > 0) {
    doc.fontSize(10).font('Helvetica-Bold').text('Claim Line Items', 50, doc.y);
    doc.moveDown(0.4);

    const cols = [
      { label: 'Code',        w: 55,  align: 'left' },
      { label: 'Description', w: 160, align: 'left' },
      { label: 'Done %',      w: 48,  align: 'right' },
      { label: 'Value to Date', w: 72, align: 'right' },
      { label: 'Prev Claimed', w: 70, align: 'right' },
      { label: 'This Claim',  w: 70,  align: 'right' },
    ];
    let cx = 50;
    const hy = doc.y;
    doc.rect(50, hy, W, 16).fill('#1F3864');
    cols.forEach(col => {
      doc.fillColor('white').fontSize(8).font('Helvetica-Bold')
         .text(col.label, cx + 2, hy + 4, { width: col.w - 4, align: col.align });
      cx += col.w;
    });
    doc.fillColor('black');

    let rowY = hy + 18;
    items.forEach((item, idx) => {
      if (rowY > 720) { doc.addPage(); rowY = 50; }
      if (idx % 2 === 1) doc.rect(50, rowY, W, 14).fill('#F5F5F5').fillColor('black');
      const vals = [
        item.item_code || '—',
        (item.description || '').substring(0, 48),
        `${Number(item.cumulative_pct).toFixed(0)}%`,
        fmtRM(item.cumulative_value),
        fmtRM(item.previous_value),
        fmtRM(item.this_value),
      ];
      cx = 50;
      cols.forEach((col, ci) => {
        doc.fontSize(8).font('Helvetica')
           .text(vals[ci], cx + 2, rowY + 3, { width: col.w - 4, align: col.align });
        cx += col.w;
      });
      rowY += 14;
    });

    doc.rect(50, rowY, W, 0.5).fill('#AAAAAA').fillColor('black');
    doc.y = rowY + 8;
  }

  // ── Summary ──────────────────────────────────────────────────
  doc.moveDown(0.5);
  const summaryX = 340;
  const summaryW = 205;
  const summRow = (label, val, bold = false) => {
    const y = doc.y;
    doc.fontSize(9).font(bold ? 'Helvetica-Bold' : 'Helvetica')
       .text(label, summaryX, y, { width: 110 })
       .text(val, summaryX + 110, y, { width: 95, align: 'right' });
    doc.y = y + 14;
  };
  summRow('This Claim:', fmtRM(claim.amount));
  if (Number(claim.tax_amount) > 0)
    summRow(`SST/GST (${claim.tax_rate}%):`, fmtRM(claim.tax_amount));
  summRow('Retention:', `(${fmtRM(claim.retention_amount)})`);
  doc.moveTo(summaryX, doc.y).lineTo(summaryX + summaryW, doc.y).lineWidth(0.5).stroke('#1F3864');
  doc.y += 4;
  summRow('Net Payable:', fmtRM(claim.net_amount), true);

  // ── Footer ───────────────────────────────────────────────────
  const pageH = doc.page.height;
  doc.fontSize(8).fillColor('#888888')
     .text('Generated by ContractOS', 50, pageH - 50, { align: 'center', width: W });

  doc.end();
}

// Pipe a payment certificate PDF into res.
function buildCertPdf(res, { cert, claim, tenant }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${cert.cert_number}.pdf"`);
  doc.pipe(res);

  const W = doc.page.width - 100;

  doc.fontSize(18).font('Helvetica-Bold').text(tenant.company_name || 'ContractOS', 50, 50);
  if (tenant.address) doc.fontSize(9).font('Helvetica').text(tenant.address, 50, 72);
  if (tenant.phone) doc.fontSize(9).text(`Tel: ${tenant.phone}`);
  if (tenant.ssm_number) doc.fontSize(9).text(`SSM: ${tenant.ssm_number}`);

  doc.fontSize(20).font('Helvetica-Bold').text('PAYMENT CERTIFICATE', 350, 50, { align: 'right', width: 195 });
  doc.moveTo(50, 120).lineTo(545, 120).lineWidth(2).stroke('#1F3864');

  doc.y = 132;
  const row = (label, val) => {
    doc.fontSize(9).font('Helvetica-Bold').text(label, 50, doc.y, { continued: true })
       .font('Helvetica').text(`  ${val}`);
  };
  row('Certificate No:', cert.cert_number);
  row('Project:', cert.project_name || '—');
  row('Certificate Date:', fmtDate(cert.cert_date));
  row('Due Date:', fmtDate(cert.due_date));
  if (claim) row('Claim Reference:', claim.claim_number || '—');
  row('Status:', cert.status.replace('_', ' ').toUpperCase());
  if (cert.notes) { doc.moveDown(0.3); row('Notes:', cert.notes); }

  doc.moveDown(1.5);

  // Amounts box
  const boxY = doc.y;
  doc.rect(200, boxY, 345, 80).fill('#F0F4F8').fillColor('black');
  doc.fontSize(11).font('Helvetica-Bold').text('Certified Amount', 210, boxY + 10);
  doc.fontSize(22).font('Helvetica-Bold').fillColor('#1F3864')
     .text(fmtRM(cert.certified_amount), 210, boxY + 28);
  doc.fillColor('black').fontSize(9).font('Helvetica');
  if (Number(cert.amount_paid) > 0) {
    doc.text(`Paid to date: ${fmtRM(cert.amount_paid)}`, 210, boxY + 56);
    doc.text(`Balance: ${fmtRM(Number(cert.certified_amount) - Number(cert.amount_paid))}`, 380, boxY + 56);
  }

  doc.y = boxY + 94;
  doc.moveDown(1);

  // Signature lines
  const sigY = doc.y + 40;
  doc.moveTo(50, sigY).lineTo(220, sigY).lineWidth(0.5).stroke('#333333');
  doc.moveTo(330, sigY).lineTo(500, sigY).stroke('#333333');
  doc.fontSize(8).fillColor('#555555')
     .text('Authorised by (Contractor)', 50, sigY + 4)
     .text('Acknowledged by (Client)', 330, sigY + 4);

  const pageH = doc.page.height;
  doc.fontSize(8).fillColor('#888888')
     .text('Generated by ContractOS', 50, pageH - 50, { align: 'center', width: W });

  doc.end();
}

module.exports = { buildClaimPdf, buildCertPdf };
